### PR TITLE
fix footer HackSC copyright

### LINKED ISSUE #368: Update Odyssey Footer
This is the footer for Odyssey. We need to update the Copyright and hackers@hacksc.com email if it is incorrect.

Screen Shot 2020-09-17 at 8 32 54 PM

### PR DESCRIPTION
**Pull request by abigger87**
Closes #368

### CODE REVIEW

File: components/Footer.tsx [hunk 1]
```diff
@@ -32,7 +32,7 @@ const Footer = () => {
               <img src={Twitter} />
             </a>
           </SocialLinks>
-          <Copyright>HackSC 2019 &copy;</Copyright>
+          <Copyright>HackSC 2020 &copy;</Copyright>
```
Comment (jasonsilberman) [inline components/Footer.tsx:35]: Might as well dynamically render date:
```suggestion
          <Copyright>HackSC {(new Date()).getFullYear()} &copy;</Copyright>
```

**Review by jasonsilberman — APPROVED** [review]
🚢 ship it
